name: "Setup Cordova"
description: "Setup your GitHub Actions workflow with Apache Cordova."
author: "oxr463"
branding:
  color: black
  icon: code

runs:
  using: 'node12'
  main: '/bin/sh ./setup-cordova.sh'
