name: "Setup Cordova"
description: "Setup your GitHub Actions workflow with Apache Cordova."
author: "oxr463"
branding:
  color: black
  icon: smartphone

runs:
  using: "docker"
  image: "Dockerfile"
